---

- name: 1-1-4-createLayer3Interface：创建3层网络接口，并配置IP地址
  hosts: gateway
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:

    - name: 显示交换机的硬件及版本信息
      ce_interface:
