---

- name: 1-1-3-createPortChannel：创建port-channel
  hosts: gateway
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:
  - name: 创建port-channel100，并将10G1/0/45加入到port-channel
    ce_eth_trunk:
      trunk_id: '100'
      members: ['40GE1/0/1']
      mode: 'lacp-static'
      state: present
      provider: '{{ cli }}'
