---

- name: 1-3-deviceBaseConfiguration：交换机的基本配置
  hosts: gateway
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:
  - name: 配置NTP
    ce_ntp:
      server: 192.168.0.99
      source_int: loopback0
      is_preferred: enable
      provider: "{{ cli }}"


  - name: 配置syslog

  - name: 配置snmp服务器、通知类型
    ce_snmp_target_host:
      state:  present
      address:  192.168.0.99
      notify_type:  trap
      security_name: netcli
      security_model:  v2c
      provider: "{{ cli }}"

  - name: 配置snmp服务版本
    ce_config:
      lines: snmp-agent sys-info version v2c v3
      match: exact
      provider: "{{ cli }}"

  - name: 配置snmp community
    ce_snmp_community:
      state:  present
      community_name:  www.netcli.net
      access_right:  read
      provider: "{{ cli }}"

  - name: 配置snmp trap
    ce_snmp_traps:
      state:  present
      feature_name:  all
      provider: "{{ cli }}"

  - name: 配置netconf
    ce_config:
      lines:  protocol inbound ssh ipv4 port 830
      before: netconf
      provider: '{{ cli }}'

  - name: 配置LLDP
    ce_config:
      lines: lldp enable
      provider: '{{ cli }}'


  - name: 配置netflow

  - name: 配置保存

  - name: 配置回滚

