---

- name: 1-3-deviceBaseConfiguration：交换机的基本配置
  hosts: gateway
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:
  - name: 配置NTP
    ce_ntp:
      server: 192.168.0.99
      source_int: loopback0
      is_preferred: enable
      provider: "{{ cli }}"
  - name: configure clock timezone as BEIJING
    ce_config:
      lines:
        - clock timezone BeiJing add 8
      match: exact
      provider: '{{ cli }}'

  - name: 配置snmp服务器、通知类型
    ce_snmp_target_host:
      state:  present
      address:  192.168.0.99
      notify_type:  trap
      security_name: netcli
      security_model:  v2c
      provider: "{{ cli }}"

  - name: 配置snmp服务版本
    ce_config:
      lines: snmp-agent sys-info version v2c v3
      match: exact
      provider: "{{ cli }}"

  - name: 配置snmp community
    ce_snmp_community:
      state:  present
      community_name:  www.netcli.net
      access_right:  read
      provider: "{{ cli }}"

  - name: 配置snmp trap
    ce_snmp_traps:
      state:  present
      feature_name:  all
      provider: "{{ cli }}"

  - name: 配置netconf
    ce_config:
      lines:  protocol inbound ssh ipv4 port 830
      before: netconf
      provider: '{{ cli }}'

  - name: 配置LLDP
    ce_config:
      lines: lldp enable
      provider: '{{ cli }}'


  - name: 配置netflow
    ce_sflow:
      agent_ip: 1.1.1.1             #local IP, display in log, marks the device which send the sflow
      collector_id: '1'
      collector_ip: 192.168.0.99    #sflow server IP, to collect and process sflow informations
      provider: '{{ cli }}'


  - name: 配置info-center服务
    ce_info_center_global:
       info_center_enable: 'true'
       is_default_vpn: 'true'
       state: present
       level: warning
       ip_type: ipv4
       server_ip: 192.168.0.99
       source_ip: 1.1.1.1
       provider: '{{ cli }}'


  - name: 配置syslog服务
    ce_info_center_log:
       log_buff_enable: 'true'
       log_enable: 'true'
       state: present
       log_level: warning
       log_time_stamp: formatdate_millisecond
       provider: '{{ cli }}'

  - name: 配置syslog-trap服务
    ce_info_center_trap:
       trap_buff_enable: 'true'
       trap_enable: 'true'
       state: present
       trap_level: warning
       trap_time_stamp: formatdate_millisecond
       provider: '{{ cli }}'

  - name: 保存配置
    ce_config:
      lines:
        - save
      match: exact
      provider: '{{ cli }}'
