---

- name: 1-5-1-aclConfig：创建访问控制列表
  hosts: gateway
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:

    #创建标准ACL，序号2001,允许192.168.1.0/24访问
    - name: '创建并配置标准ACL，允许192.168.1.0/24访问'
      ce_acl:
        state: present
        acl_name: '2001'
        rule_action: permit
        acl_step: '8'
        source_ip: '192.168.1.0'
        src_mask: '24'
        provider: "{{ cli }}"

    #创建高级ACL，name：to_webServer,允许外部用户访问192.168.0.10:443
    - name: '创建并配置高级ACL，允许外部用户访问web服务器的443端口'
      ce_acl_advance:
        state:  present
        acl_name: 'to_webServer'
        rule_name:  'test_rule'
        rule_id:  '110'
        rule_action:  permit
        protocol:  tcp
        dest_ip: '192.168.0.10'
        dest_mask: '32'
        dest_port_op: eq
        dest_port_begin: '443'
        provider: "{{ cli }}"