---

- name: 2-1-3-createPortChannel：创建port-channel
  hosts: tor
  gather_facts: no
  connection: local

  tasks:
    - name: 配置与gateway互联的port-channel 100，并将FortyGigE1/0/51加入到port-channel100中
      comware_portchannel:
        group: '100'
        members:
          - FortyGigE1/0/51
        type: bridged
        lacp_mode: active
        mode: dynamic
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        hostname: "{{ ansible_host }}"

