---

- name: test route protocols
  hosts: tor
  gather_facts: no
  connection: local

  tasks:

    - name: test static route to Gateway loopback1
      comware_command:
        command:
          -  ip route-static 1.1.1.1 255.255.255.255 192.168.0.254
        type: config
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        hostname: "{{ ansible_host }}"

    - name: make Gateway to OSPF neighbor in OSPF process 100
      comware_command:
        command:
          - ospf 100 router-id 1.1.1.2
          -  bandwidth-reference 40000
          -  area 0.0.0.0
          -  network 1.1.1.2 0.0.0.0
          -  network 192.168.0.0 0.0.0.255
          - interface vlan10
          -  ospf network-type p2p
        type: config
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        hostname: "{{ ansible_host }}"


    - name: make Gateway to iBGP neighbor in BGP AS 65512
      comware_command:
        command:
          - bgp 65512
          - router-id 1.1.1.2
          - peer 1.1.1.1 as-number 65512
          - peer 1.1.1.1 connect-interface LoopBack0
          - address-family ipv4 unicast
          - network 10.1.1.2 255.255.255.255
          - peer 1.1.1.1 enable
          - peer 1.1.1.1 next-hop-local
        type: config
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        hostname: "{{ ansible_host }}"