---

  - name: 2-3-deviceBaseConfiguration：交换机的基本配置
    hosts: tor
    gather_facts: no
    connection: local

    tasks:

      - name: 配置NTP服务
        comware_command:
          command:
            - ntp-service enable
            - ntp-service refclock-master 2
            - ntp-service unicast-server 192.168.0.99
          type: config
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          hostname: "{{ ansible_host }}"

      - name: 配置syslog服务
        comware_command:
          command:
            - info-center enable
            - info-center source default console deny
            - info-center source ftp console level warning

