---

- name: VLAN Automation with Ansible on HP Com7 Devices
  hosts: netcli
  gather_facts: no
  connection: local

  tasks:

    - name: ensure VLAN 100 exists
      comware_vlan: vlanid=100 name=VLAN10_WEB descr=LOCALSEGMENT username={{ ansible_ssh_user }} password={{ ansible_ssh_pass }} hostname={{ ansible_host }}

    - name: ensure VLAN 200 exists
      comware_vlan: vlanid=200 name=VLAN20 state=present username={{ ansible_ssh_user }} password={{ ansible_ssh_pass }} hostname={{ ansible_host }}

    - name: ensure VLAN 100 does not exist
      comware_vlan: vlanid=100 state=absent username={{ ansible_ssh_user }} password={{ ansible_ssh_pass }} hostname={{ ansible_host }}