---

- name: eth_trunk module test
  hosts: netcli 
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:
  - name: 创建VLAN10
    ce_vlan:
      vlan_id: 10
      name: WEB
      state: present
      provider: "{{ cli }}"

  - name: 配置web SVI
    ce_interface:
      interface: vlanif10
      description: 'WEB SERVER GATEWAY'
      provider: '{{ cli }}'

  - name: 为SVI 10分配IP地址
    ce_ip_interface:
      interface:  Vlanif10
      version: v4
      state: present
      addr: 192.168.1.254
      mask: 24
      provider: '{{ cli }}'
 
  - name: 创建loopback0
    ce_interface:
      interface: loopback0
      description: 'outside user'
      provider: '{{ cli }}'

  - name: loopback0配置IP地址
    ce_ip_interface:
      interface: loopback0
      addr: 10.1.1.1
      mask: 32
      provider: '{{ cli }}'



